name: Build Zombie Cafe Mod APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_HOME: /usr/local/lib/android/sdk/ndk/26.1.10909125

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool openjdk-17-jdk zipalign unzip

      - name: Download original APK
        run: |
          mkdir original
          curl -L -o original/zombie-cafe-original.apk "https://example.com/zombie-cafe-original.apk"

      - name: Extract original APK
        run: |
          apktool d -f -o build original/zombie-cafe-original.apk

      - name: Extract original libZombieCafeAndroid.so
        run: |
          mkdir -p build/lib/armeabi-v7a
          unzip -j original/zombie-cafe-original.apk "lib/armeabi/libZombieCafeAndroid.so" -d build/lib/armeabi-v7a

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true

      - name: Build libZombieCafeExtension.so
        run: |
          cd src/lib/cpp
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-8
          make

      - name: Copy libZombieCafeExtension.so into APK
        run: |
          cp src/lib/cpp/build/libZombieCafeExtension.so build/lib/armeabi-v7a/

      - name: Rebuild APK with both .so files
        run: |
          apktool b build -o build/out/zombie-cafe-revival-unsigned.apk

      - name: Sign APK
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass zombiecafe -alias zombiecafe -keypass zombiecafe -dname "CN=ZombieCafe, OU=Dev, O=Capcom, L=Osaka, ST=Japan, C=JP" -keyalg RSA -keysize 2048 -validity 10000
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore -storepass zombiecafe build/out/zombie-cafe-revival-unsigned.apk zombiecafe

      - name: Align APK
        run: |
          zipalign -v 4 build/out/zombie-cafe-revival-unsigned.apk build/out/zombie-cafe-revival-patched.apk

      - name: Upload final APK
        uses: actions/upload-artifact@v3
        with:
          name: zombie-cafe-revival-patched
          path: build/out/zombie-cafe-revival-patched.apk