name: Build Zombie Cafe Mod APK

on:
  push:
    branches:
      - main
  pull_request:

env:
  ANDROID_NDK_VERSION: "21.4.7075529"
  ANDROID_API_LEVEL: "28"
  BUILD_TOOLS: "30.0.3"
  KEYSTORE_PASSWORD: "zombiecafe"
  KEY_ALIAS: "alias_name"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          api-level: ${{ env.ANDROID_API_LEVEL }}
          build-tools: ${{ env.BUILD_TOOLS }}

      - name: Build C++ extension with CMake & Make
        working-directory: src/lib/cpp
        run: |
          mkdir -p build
          cd build
          cmake ../ \
            -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-8
          make

      - name: Run Go build_tool
        run: go run ./tool/build_tool/ -i src/ -o build/

      - name: Copy native library into armeabi-v7a folder
        run: |
          mkdir -p build/lib/armeabi-v7a
          cp src/lib/cpp/build/libZombieCafeExtension.so build/lib/armeabi-v7a/libZombieCafeExtension.so

      - name: Download apktool
        run: |
          curl -L -o apktool.jar https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar

      - name: Rebuild APK with apktool
        run: |
          java -jar apktool.jar b build -o build/out/zombie-cafe-revival-balance.apk

      - name: Zipalign APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/${{ env.BUILD_TOOLS }}/zipalign -v -p 4 \
            build/out/zombie-cafe-revival-balance.apk \
            build/out/zombie-cafe-revival-balance-aligned.apk

      - name: Sign APK with apksigner (v2+)
        run: |
          $ANDROID_SDK_ROOT/build-tools/${{ env.BUILD_TOOLS }}/apksigner sign \
            --ks debug.keystore \
            --ks-key-alias ${{ env.KEY_ALIAS }} \
            --ks-pass pass:${{ env.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ env.KEYSTORE_PASSWORD }} \
            --out build/out/zombie-cafe-revival-balance-signed.apk \
            build/out/zombie-cafe-revival-balance-aligned.apk

      - name: Upload modded APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: zombie-cafe-revival-balance
          path: build/out/zombie-cafe-revival-balance.apk